apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: arma3-claim0
  name: arma3-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40000Mi
status: {}